### ISSUE TITLE
Jenkins setup completed

### ISSUE THREAD

**Issue by VishalUzumaki** [airavata-courses/IU-Witcher-2020#104]
Jenkins set up completed for API gateway, UI , and User Management.
Created Jenkins job that triggers build on git push using webhook.

**Comment by sanyam1997** [comment]
The Jenkins is set up and complete and all the microservices are building and running appropriately

**Comment by sanyam1997** [comment]
![Uploading Screenshot from 2020-03-20 19-41-53.png…]()

**Comment by sanyam1997** [comment]
![Screenshot from 2020-03-20 19-45-09](https://user-images.githubusercontent.com/19321068/77214000-51c1d780-6ae3-11ea-98ae-88e0ae34b8b7.png)
