### ISSUE TITLE
Error while accessing API gateway directly

### ISSUE THREAD

**Issue by vivekshresta** [airavata-courses/IU-Witcher-2020#110]
Why is it giving this error on accessing API gateway address through URL directly from the web-browser?

![image](https://user-images.githubusercontent.com/55638867/77203696-6bedbc80-6ac7-11ea-8271-00bb3ece928f.png)

**Comment by VishalUzumaki** [comment]
We are routing the root url of API gateway to the user management and hence it  requires username and password parameters (which we are providing from front end), while trying to access directly this values will be null and hence will throw an error.

**Comment by vivekshresta** [comment]
Issue resolved.
