### ISSUE TITLE
Unable to build docker image when running jenkins job

### ISSUE THREAD

**Issue by aksrajvanshi** [airavata-courses/IU-Witcher-2020#111]
When I try to build a docker image while running a Jenkins job, it gives me an error. Please look into this issue.

![docker-image](https://user-images.githubusercontent.com/16722550/77208911-4a92cd80-6ad3-11ea-806e-e36bf1e3f547.jpeg)

**Comment by sanyam1997** [comment]
I have added the sudo command in the following because as per the online reference, it clearly states that docker build needs sudo to be able to run the command.

**Comment by sanyam1997** [comment]
I think sudo alone is not working for our Jenkins instance. I tried it now. I have one solution which I found online and seems credible. I will try to implement this and see if it works.

**Comment by sanyam1997** [comment]
![Screenshot from 2020-03-20 18-29-43](https://user-images.githubusercontent.com/19321068/77210991-cc392a00-6ad8-11ea-862a-07a409a7bf8e.png)

**Comment by aksrajvanshi** [comment]
Thanks.
