### ISSUE TITLE
No readme present

### ISSUE THREAD

**Issue by ghost** [airavata-courses/IU-Witcher-2020#113]
I couldnt find the readme and information about the project.

**Comment by akshaygpt** [comment]
Hi @shivamriky Please follow the Wiki guidelines [here](https://github.com/airavata-courses/IU-Witcher-2020/wiki/Jenkins)

**Comment by ghost** [comment]
@sanyam1997 The link you provided is blank and it only has the name of teammates

**Comment by sanyam1997** [comment]
Updated the right link.
