### ISSUE TITLE
Could not find information about CI/CD pipeline 

### ISSUE THREAD

**Issue by ghost** [airavata-courses/IU-Witcher-2020#114]

**Comment by sanyam1997** [comment]
The wiki has been updated for the same

https://github.com/airavata-courses/IU-Witcher-2020/wiki/Jenkins

**Comment by ghost** [comment]
Can you point how to see your CI/CD pipeline??

**Comment by sanyam1997** [comment]
All the jobs running on the Jenkins pipeline can be accessed on the instance IP as mentioned in the wiki.
