### ISSUE TITLE
Istio ingress gateway

### ISSUE THREAD

**Issue by VishalUzumaki** [airavata-courses/IU-Witcher-2020#120]
setup istio on local kubernetes cluster and setup istio ingress gateway.
setup virtual service to UI.
Traffic visualization using Kiala

![image](https://user-images.githubusercontent.com/22035884/79411687-180cb100-7f69-11ea-8f1d-6307fc2d8415.png)

**Comment by sanyam1997** [comment]
![Screenshot from 2020-04-23 18-38-17](https://user-images.githubusercontent.com/19321068/80764562-f7b72780-8b0e-11ea-8a6a-585eb39682c5.png)

Made the gateway and able to access it
