### ISSUE TITLE
While logging in, on direct clicking on Search Button without any data, it sends empty string to Back-end 

### ISSUE THREAD

**Issue by shindedarshan** [airavata-courses/IU-Witcher-2020#50]
The button should be disabled when there is no data entered in the search.

**Comment by VishalUzumaki** [comment]
We are using state in ReactJs and in that the default value for search is a empty string, when any element is selected from Drop down menu the search is updated. Hence you need to select one of the elements from the drop down before submitting.

**Comment by shindedarshan** [comment]
I think this issue still persists. The button should be disabled when no element selected.

**Comment by VishalUzumaki** [comment]
I have added default value to search, so now it should work.

**Comment by shindedarshan** [comment]
Now this functionality working correct. Hence marking it as close
