### ISSUE TITLE
Database is not working for User Management Microservice 

### ISSUE THREAD

**Issue by knikharg** [airavata-courses/IU-Witcher-2020#55]

**Comment by knikharg** [comment]
Database connection to User Management microservice through MySQL seems to be failing

**Comment by VishalUzumaki** [comment]
There can be several reasons:
1) You have to change database location from "localhost" to the location where your database is hosted on your system.
2) Upgrade PHP to higher version from php 5.0 as "the MySQLi extension was introduced with PHP version 5.0"
