### ISSUE TITLE
Setup a connection to `Jenkins` over `ssh` and run it on a local port

### ISSUE THREAD

**Issue by akshaygpt** [airavata-courses/IU-Witcher-2020#93]

**Comment by sanyam1997** [comment]
Jenkins connection established for API-gateway. Running and functional for every commit.

**Comment by sanyam1997** [comment]
Jenkins connection established for User-management. Running and functional for every commit.

**Comment by sanyam1997** [comment]
Jenkins connection established for UI. Running and functional for every commit.

**Comment by sanyam1997** [comment]
Jenkins's connection established for Data Retrieval. Running and functional for every commit.
Only connection with rabbitmq remaining

**Comment by sanyam1997** [comment]
Jenkins's connection established for Model Execution. Running and functional for every commit.
Only connection with rabbitmq remaining

**Comment by sanyam1997** [comment]
Jenkins connection
![Uploading Screenshot from 2020-03-20 19-41-53.png…]()
 setup for all the services.
