### ISSUE TITLE
Setup docker image building on Jenkins

### ISSUE THREAD

**Issue by akshaygpt** [airavata-courses/IU-Witcher-2020#94]

**Comment by VishalUzumaki** [comment]
Able to run the code from develop branch in jenkins shell.

**Comment by sanyam1997** [comment]
The code is functional now for data retrieval, model execution, and post-processing microservices. Besides, the files are able to build on dockerhub. Need to add rabbitmq to be able to run. Besides, for now I have updated the dockerfile images as python3 simple lightweight images. If the dockerfile demands Operating System Images, the code can be uncommented to make it functional for OS-based images like debain which is in comment for now.

**Comment by sanyam1997** [comment]
Jenkins pushing images and removing the files which consume extra memory on the instance.
